
version: '3.5'

services:
  web:
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    container_name: luckystar
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secretpassword
    image: lucky-star
    volumes:
      - .:/lucky-star
    ports:
      - "3001:3001"
    expose:
      - "3001"
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: lucky-star-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
    ports: ["5434:5434"]
    expose: ["5434"]
