
version: '3.5'

services:
  web:
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    container_name: luckystar
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secretpassword
    image: lucky-star
    volumes:
      - .:/lucky-star
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:10.5
    container_name: lucky-star-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
    ports: ["5432:5432"]
    expose: ["5432"]
